spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      credentials:
        encoded-key: ${GCP_CREDENTIALS}

emotion-prediction:
  uri: ${EMOTION_SERVICE_URL}
