spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
  datasource:
    url: "jdbc:mysql://localhost:3306/sponews"
    username: "sponewsapp"
    password: "rocketracoon"
    name: "sponews"

  jpa:
    hibernate:
      ddl-auto: update