spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
  datasource:
    url: "jdbc:postgresql://localhost:5432/sponews"
    username: "sponewsapp"
    password: "rocketracoon"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    gcp:
      project-id: "file-upload-1332c"
      credentials:
        default-scopes: "www.googleapis.com/auth/devstorage.read_write"
        location: "classpath:firebase-storage-credentials.json"

emotion-prediction:
  uri: "http://localhost:5000/predict"
