spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
  datasource:
    url: "jdbc:postgresql://localhost:5432/sponews"
    username: "sponewsapp"
    password: "rocketracoon"

  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update

emotion-prediction:
  uri: "http://localhost:5000/predict"